version: "3"
services:
  angular-app-alquiler:
    build:
      context: ./angular-app/alquiler
    ports:
      - "3001:80"

  angular-app-ventas:
    build:
      context: ./angular-app/venta
    ports:
      - "3002:80"

  host-app:
    build:
      context: ./host-app
    ports:
      - "3000:80"
